### ISSUE TITLE
Adding <p rend="flush"> rendering, which was able in P4

### ISSUE THREAD

**Issue by tubesoft** [IUBLibTech/newton_chymistry#107]
I realized that sometimes we might need `<p rend="flush">` to supress the indentation of the first line of a paragraph.

Also, `<p>` tag also renders margins on the top and bottom of the paragraph. Sometimes we also don't need them. I am now going to make `<p rend="flush-all">` for that.

I am adding some code at `tei.css` like this:
```css
.tei-p {
	margin-top: 1em;
	margin-bottom: 1em;
	line-height: 1.5;
	white-space: normal;
	text-indent: 1.5em;
}

.tei-p.rend-flush {
    text-indent: 0em
}

.tei-p.rend-flush-all {
	margin-top: 0em;
    margin-bottom: 0em;
    text-indent: 0em
}
```

I am making a note here for the future review.
